### ISSUE TITLE
projectile integration

### ISSUE THREAD

**Issue by gonewest818** [alphapapa/bufler.el#10]
How would you envision `projectile` to be integrated:
* implement `auto-projectile` as its own grouping mechanism?
* on switching buffers set the workspace to the projectile project (if projectile detects one) and then let workspace grouping take care of the rest?
* or, some other mechanism?

**Comment by alphapapa** [comment]
I would think that there should be an `auto-projectile` rule, basically the same as `auto-project` but using Projectile's backend for project detection.  I don't think any other changes would be required.

**Comment by gonewest818** [comment]
Thanks
