### ISSUE TITLE
Programmatically switch frame's workspace

### ISSUE THREAD

**Issue by antifuchs** [alphapapa/bufler.el#16]
I just tried bufler, and it seems extremely like what I want: A way to change/restrict "what I'm working on" based on projects I'm in. I set it up to automatically group by `project.el` projects via `auto-project`, and I have a shortcut that opens a magit repository; now I would like to set the frame's workspace to the project-inferred one whenever I use that shortcut.

Unfortunately, I could not find a way to do it - the docs for `bufler-workspace-frame-set` mention a "path", but passing in the project entry from `bufler-buffers` doesn't seem to do it, and neither does just passing the workspace name `"Project: /Users/asf/Hacks/kleinhirn"` - that creates an empty workspace with no buffers in it. So, my questions are:

* What shape should the `path` argument have?
* How can I construct one from the current buffer (which already is in the right workspace, afaict)?

Thanks in advance!

**Comment by TheBB** [comment]
In *bufler-workspace.el* this is how it's done (from *bufler-workspace-switch-buffer*).

      (bufler-workspace-frame-set
       (butlast (bufler-group-tree-leaf-path (bufler-buffers) selected-buffer)))

A path is a list, and the `(butlast ...)` expression computes a sort of "best guess" path by removing the last element (which is the buffer).

**Comment by alphapapa** [comment]
@TheBB Thanks.  :)

@antifuchs Yes, paths to buffers are lists of strings or nil, ending with the buffer, so the path to a buffer without its last element is the path to the buffer's directly containing group.  You can pass that list to `bufler-workspace-frame-set`.

FYI, in future versions this may change slightly, e.g. the group keys may be structs with the string in a slot.  It seems necessary to refactor some of the group path-related code to simplify it.  However, that probably won't happen for a while, and I will tag a stable release before pushing that kind of change to `master`, so you won't be forced to deal with that change at the time, if you don't want to.

**Comment by antifuchs** [comment]
Oh myyyy, thanks so much, you two! With the form @TheBB provided, I could set the following function which sets the frame up to contain the project:

``` emacs-lisp
(add-hook 'asf-quick-switch-project-hook
          (defun asf--set-bufler-project-workspace ()
            (bufler-workspace-frame-set
             (butlast (bufler-group-tree-leaf-path (bufler-buffers) (current-buffer))))))
```

Closing this issue as resolved - thanks again!
