### ISSUE TITLE
tab-line as an alternative to tab-bar for macOS?

### ISSUE THREAD

**Issue by antifuchs** [alphapapa/bufler.el#17]
I'm on a mac, and the graphical version of emacs has no visible tab-bar implemented yet, so none of the convenient workspace-switching tools work for me /-:

Would it be possible to disable the tab-bar and only use tab-line (which is working & lists all the buffers, something I don't really need) to list the available workspaces? I've tried a few things, but the most success I had with something like this:

``` emacs-lisp
(defun asf-bufler-global-tab-line-mode-activate ()
  (setf tab-line-tabs-function #'bufler-workspace-tabs)
  (tab-bar-mode 0)
  (global-tab-line-mode 1))

(defun asf--switch-to-tab-n (n)
  `(lambda ()
     (interactive)
     (bufler-workspace-tabs--tab-bar-select-tab ,n)))

(bind-key "s-1" (asf--switch-to-tab-n 1))
(bind-key "s-2" (asf--switch-to-tab-n 2))
(bind-key "s-3" (asf--switch-to-tab-n 3))
(bind-key "s-4" (asf--switch-to-tab-n 4))
(bind-key "s-5" (asf--switch-to-tab-n 5))
(bind-key "s-6" (asf--switch-to-tab-n 6))
(bind-key "s-7" (asf--switch-to-tab-n 7))
(bind-key "s-8" (asf--switch-to-tab-n 8))
(bind-key "s-9" (asf--switch-to-tab-n 9))
(bind-key "s-0" (asf--switch-to-tab-n 10))
```

So far, this kiiiinda gets the workspaces listed on the tab-line, but clicking them doesn't work, and there is no feedback on which tab is the "selected" workspace. That's not great, so I figured I'd open an issue here so we can discuss.

I guess one alternative for macOS users would be to implement a reduced-feature-set version that displays the tabs in the minibuffer/echo area (a la mini-mode-line)...

**Comment by alphapapa** [comment]
As you have probably guessed, I don't use a Mac.  I'd prefer to not add platform-specific workarounds to this project.  If you're able to come up with some code to work around this problem on a Mac, I'd be willing to mention it in the documentation.

**Comment by antifuchs** [comment]
I ended up giving up trying to use the mac tab-bar with bufler, as things like `tab-bar-switch-to-tab` (by name) doesn't work with the advice that's in place. What does work, however, is combining eyebrowse (and likely other window configuration systems) with bufler!

This customization code helps a lot:

``` emacs-lisp
(defvar asf--bufler-workspace-assignments (vector nil nil nil nil nil nil nil nil nil nil)) ; 10.

(add-hook 'bufler-workspace-set-hook
          (defun asf-register-bufler-ws-with-eyebrowse (workspace)
            (setf (aref asf--bufler-workspace-assignments (eyebrowse--get 'current-slot))
                  workspace)))

(add-hook 'eyebrowse-post-window-switch-hook
          (defun asf-eyebrowse-bufler-switch-group ()
            (let ((eb-workspace (eyebrowse--get 'current-slot)))
              (bufler-workspace-frame-set (aref asf--bufler-workspace-assignments eb-workspace)))))
```

Now, whenever I switch to one of the eyebrowse window configs (to one of the 10 that I have bound to `s-<number key>`, bufler switches workspaces too; and whenever my bufler frame workspace changes, that gets recorded so eyebrowse can keep up, as well.

I'm pretty happy with this solution, despite not being tab-bar based - hope this customization is useful to somebody else. I'll close this issue.
