### ISSUE TITLE
bufler-workspace-tabs-mode breaks tab-bar--current-tab-index

### ISSUE THREAD

**Issue by progfolio** [alphapapa/bufler.el#18]
Another great package! `bufler-workspace-tabs-mode` looks particularly promising.
I've been experimenting with it and ran into a minor issue:
`bufler-workspace-tabs` seems to break `tab-bar--current-tab-index`

I haven't had much time to look into the source, but I did note your commentary on `bufler-workspace-tabs` and the complicated requirements of its implementation.
An ECM:

    (bufler-workspace-tabs-mode)
    (condition-case err
        (tab-bar--current-tab-index)
      (error err))

returns:

(wrong-type-argument framep nil)

Here's a backtrace:

    Debugger entered--Lisp error: (wrong-type-argument framep nil)
    select-frame(nil norecord)
    (progn (select-frame frame 'norecord) (cl-labels ((tab-type (path) (if (equal path (frame-parameter nil 'bufler-workspace-path)) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string (list path)) (list (if (car path) (list ...) (list ...))))) (workspace-to-tab (workspace &optional type) (-let* (((&plist :name :path) workspace)) (list (or type (tab-type path)) (cons 'name (car name)) (cons 'path path)))) (path-top-level (path) (pcase-exhaustive path (`(... ... \, _rest) (ignore first second) (cl-subseq path 0 2)) (`(... \, _rest) (list first)))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths (bufler-buffers))) (group-paths (mapcar #'butlast buffer-paths)) (top-level-paths (mapcar #'path-top-level group-paths)) (top-level-workspaces (mapcar #'path-to-workspace top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces #'equal)) (tabs (mapcar #'workspace-to-tab unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil 'bufler-workspace-path) for tab in tabs for tab-path = (alist-get 'path tab) thereis (equal tab-path current-path)) (push (list 'current-tab (cons 'name (bufler-format-path ...)) (cons 'path (frame-parameter nil ...))) tabs)) tabs)))
    (unwind-protect (progn (select-frame frame 'norecord) (cl-labels ((tab-type (path) (if (equal path (frame-parameter nil ...)) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string (list path)) (list (if ... ... ...)))) (workspace-to-tab (workspace &optional type) (-let* ((... workspace)) (list (or type ...) (cons ... ...) (cons ... path)))) (path-top-level (path) (pcase-exhaustive path (`... (ignore first second) (cl-subseq path 0 2)) (`... (list first)))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths (bufler-buffers))) (group-paths (mapcar #'butlast buffer-paths)) (top-level-paths (mapcar #'path-top-level group-paths)) (top-level-workspaces (mapcar #'path-to-workspace top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces #'equal)) (tabs (mapcar #'workspace-to-tab unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil 'bufler-workspace-path) for tab in tabs for tab-path = (alist-get 'path tab) thereis (equal tab-path current-path)) (push (list 'current-tab (cons ... ...) (cons ... ...)) tabs)) tabs))) (when (frame-live-p old-frame) (select-frame old-frame 'norecord)) (when (buffer-live-p old-buffer) (set-buffer old-buffer)))
    (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame 'norecord) (cl-labels ((tab-type (path) (if (equal path ...) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string ...) (list ...))) (workspace-to-tab (workspace &optional type) (-let* (...) (list ... ... ...))) (path-top-level (path) (pcase-exhaustive path (... ... ...) (... ...))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths ...)) (group-paths (mapcar ... buffer-paths)) (top-level-paths (mapcar ... group-paths)) (top-level-workspaces (mapcar ... top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces ...)) (tabs (mapcar ... unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil ...) for tab in tabs for tab-path = (alist-get ... tab) thereis (equal tab-path current-path)) (push (list ... ... ...) tabs)) tabs))) (when (frame-live-p old-frame) (select-frame old-frame 'norecord)) (when (buffer-live-p old-buffer) (set-buffer old-buffer))))
    (with-selected-frame frame (cl-labels ((tab-type (path) (if (equal path (frame-parameter nil 'bufler-workspace-path)) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string (list path)) (list (if (car path) (list ...) (list ...))))) (workspace-to-tab (workspace &optional type) (-let* (((&plist :name :path) workspace)) (list (or type (tab-type path)) (cons 'name (car name)) (cons 'path path)))) (path-top-level (path) (pcase-exhaustive path (`(... ... \, _rest) (ignore first second) (cl-subseq path 0 2)) (`(... \, _rest) (list first)))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths (bufler-buffers))) (group-paths (mapcar #'butlast buffer-paths)) (top-level-paths (mapcar #'path-top-level group-paths)) (top-level-workspaces (mapcar #'path-to-workspace top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces #'equal)) (tabs (mapcar #'workspace-to-tab unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil 'bufler-workspace-path) for tab in tabs for tab-path = (alist-get 'path tab) thereis (equal tab-path current-path)) (push (list 'current-tab (cons 'name (bufler-format-path ...)) (cons 'path (frame-parameter nil ...))) tabs)) tabs)))
    (catch '--cl-block-bufler-workspace-tabs-- (with-selected-frame frame (cl-labels ((tab-type (path) (if (equal path (frame-parameter nil ...)) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string (list path)) (list (if ... ... ...)))) (workspace-to-tab (workspace &optional type) (-let* ((... workspace)) (list (or type ...) (cons ... ...) (cons ... path)))) (path-top-level (path) (pcase-exhaustive path (`... (ignore first second) (cl-subseq path 0 2)) (`... (list first)))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths (bufler-buffers))) (group-paths (mapcar #'butlast buffer-paths)) (top-level-paths (mapcar #'path-top-level group-paths)) (top-level-workspaces (mapcar #'path-to-workspace top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces #'equal)) (tabs (mapcar #'workspace-to-tab unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil 'bufler-workspace-path) for tab in tabs for tab-path = (alist-get 'path tab) thereis (equal tab-path current-path)) (push (list 'current-tab (cons ... ...) (cons ... ...)) tabs)) tabs))))
    (cl--block-wrapper (catch '--cl-block-bufler-workspace-tabs-- (with-selected-frame frame (cl-labels ((tab-type (path) (if (equal path ...) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string ...) (list ...))) (workspace-to-tab (workspace &optional type) (-let* (...) (list ... ... ...))) (path-top-level (path) (pcase-exhaustive path (... ... ...) (... ...))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths ...)) (group-paths (mapcar ... buffer-paths)) (top-level-paths (mapcar ... group-paths)) (top-level-workspaces (mapcar ... top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces ...)) (tabs (mapcar ... unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil ...) for tab in tabs for tab-path = (alist-get ... tab) thereis (equal tab-path current-path)) (push (list ... ... ...) tabs)) tabs)))))
    (cl-block bufler-workspace-tabs (with-selected-frame frame (cl-labels ((tab-type (path) (if (equal path (frame-parameter nil ...)) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string (list path)) (list (if ... ... ...)))) (workspace-to-tab (workspace &optional type) (-let* ((... workspace)) (list (or type ...) (cons ... ...) (cons ... path)))) (path-top-level (path) (pcase-exhaustive path (`... (ignore first second) (cl-subseq path 0 2)) (`... (list first)))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths (bufler-buffers))) (group-paths (mapcar #'butlast buffer-paths)) (top-level-paths (mapcar #'path-top-level group-paths)) (top-level-workspaces (mapcar #'path-to-workspace top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces #'equal)) (tabs (mapcar #'workspace-to-tab unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil 'bufler-workspace-path) for tab in tabs for tab-path = (alist-get 'path tab) thereis (equal tab-path current-path)) (push (list 'current-tab (cons ... ...) (cons ... ...)) tabs)) tabs))))
    (progn (if --cl-rest-- (signal 'wrong-number-of-arguments (list 'bufler-workspace-tabs (+ 1 (length --cl-rest--))))) (cl-block bufler-workspace-tabs (with-selected-frame frame (cl-labels ((tab-type (path) (if (equal path ...) 'current-tab 'tab)) (path-first (path) (cl-typecase path (string ...) (list ...))) (workspace-to-tab (workspace &optional type) (-let* (...) (list ... ... ...))) (path-top-level (path) (pcase-exhaustive path (... ... ...) (... ...))) (path-to-workspace (path) (list :name (path-first path) :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths (bufler-group-tree-paths ...)) (group-paths (mapcar ... buffer-paths)) (top-level-paths (mapcar ... group-paths)) (top-level-workspaces (mapcar ... top-level-paths)) (unique-top-level-workspaces (seq-uniq top-level-workspaces ...)) (tabs (mapcar ... unique-top-level-workspaces))) (unless (cl-loop with current-path = (frame-parameter nil ...) for tab in tabs for tab-path = (alist-get ... tab) thereis (equal tab-path current-path)) (push (list ... ... ...) tabs)) tabs)))))
    (let* ((frame (if --cl-rest-- (pop --cl-rest--) (selected-frame)))) (progn (if --cl-rest-- (signal 'wrong-number-of-arguments (list 'bufler-workspace-tabs (+ 1 (length --cl-rest--))))) (cl-block bufler-workspace-tabs (with-selected-frame frame (cl-labels ((tab-type (path) (if ... ... ...)) (path-first (path) (cl-typecase path ... ...)) (workspace-to-tab (workspace &optional type) (-let* ... ...)) (path-top-level (path) (pcase-exhaustive path ... ...)) (path-to-workspace (path) (list :name ... :path path))) (let* ((bufler-vc-refresh nil) (buffer-paths ...) (group-paths ...) (top-level-paths ...) (top-level-workspaces ...) (unique-top-level-workspaces ...) (tabs ...)) (unless (cl-loop with current-path = ... for tab in tabs for tab-path = ... thereis ...) (push ... tabs)) tabs))))))
    bufler-workspace-tabs(nil)
    tab-bar--current-tab-index()
    (progn (tab-bar--current-tab-index))
    eval((progn (tab-bar--current-tab-index)) t)
    elisp--eval-last-sexp(nil)
    eval-last-sexp(nil)
    funcall-interactively(eval-last-sexp nil)
    call-interactively(eval-last-sexp nil nil)
    command-execute(eval-last-sexp)

What initially brought this to my attention was [doom-modeline](https://github.com/seagle0128/doom-modeline).
It has a segment that displays the current tab index in the modeline and it signals (quite a few depending on the situation) errors on redisplay:

    Error during redisplay: (eval (doom-modeline-segment--workspace-name)) signaled (wrong-type-argument framep nil) [1038 times]

If there's anything more I can do to help, let me know.

Thanks again for the great package,
Nick Vollmer

**Comment by alphapapa** [comment]
Hi Nick (or should I say No Wayman?),

> Another great package! `bufler-workspace-tabs-mode` looks particularly promising.

Thanks.

> I've been experimenting with it and ran into a minor issue:
> `bufler-workspace-tabs` seems to break `tab-bar--current-tab-index`

The backtrace shows that the `frame` variable is nil instead of being the value of `(selected-frame)`.  I reproduced this on Emacs 28 by evaluating `(tab-bar--current-tab-index)`, but I can't explain why the `frame` variable is nil instead of the value of `(selected-frame)` as defined in the `cl-defun` form.  Even the backtrace shows the code that should set the variable.

> I haven't had much time to look into the source, but I did note your commentary on `bufler-workspace-tabs` and the complicated requirements of its implementation.

The complexity is entirely internal to Bufler and the way I implemented group paths.  The issue is that paths can begin with and include nil elements, but those nil elements must be omitted when displaying paths, yet they must be preserved for accessing buffers by path.  When I made that feature, I didn't realize how many places would need to account for it, and how much whack-a-mole I'd have to play when working on other features.

> What initially brought this to my attention was [doom-modeline](https://github.com/seagle0128/doom-modeline).
> It has a segment that displays the current tab index in the modeline and it signals (quite a few depending on the situation) errors on redisplay:
> 
> ```
> Error during redisplay: (eval (doom-modeline-segment--workspace-name)) signaled (wrong-type-argument framep nil) [1038 times]
> ```
> 
> If there's anything more I can do to help, let me know.

If you could figure out why the `cl-defun`-defined function is not setting the `frame` variable, that would be great.  I have no idea what's going on there.

**Comment by alphapapa** [comment]
Well that was simpler than I thought.  I didn't realize that `cl-defun` works that way, but it makes sense.  Thanks for reporting.

**Comment by progfolio** [comment]
> Hi Nick (or should I say No Wayman?
hahaha Whichever you prefer. Always good to have an alias on hand.

> When I made that feature, I didn't realize how many places would need to account for it, and how much whack-a-mole I'd have to play when working on other features.

Ah, I see. I've had similar experiences on projects. 

> Well that was simpler than I thought. 
Excellent! Glad to hear it wasn't a difficult fix.

I'm looking forward to integrating bufler into my daily workflow.
Thanks again for the great work and fast turnaround!

**Comment by alphapapa** [comment]
Thanks for the kind words.  Please keep the feedback coming!  I want to tag 0.2 and start making some other improvements, but I want to get these bugs that only come out with wider testing ironed out first.  Couldn't do it without you.  :)
