### ISSUE TITLE
Make tab-bar-switch-to-tab work

### ISSUE THREAD

**Issue by progfolio** [alphapapa/bufler.el#19]
Thanks again for the fix from yesterday. Works like a charm.

I had some time to play around with bufler some more and thought I'd document how bufler-workspace-tabs-mode interacts with tab-bar-mode.
Some of these may be non-issues depending on your vision for the mode:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Command</th>
<th scope="col" class="org-left">Epxected</th>
<th scope="col" class="org-left">Observed</th>
<th scope="col" class="org-left">Error</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">tab-bar-switch-to-tab</td>
<td class="org-left">completion prompt to switch</td>
<td class="org-left">No prompt</td>
<td class="org-left">(wrong-type-argument number-or-marker-p nil)</td>
</tr>

<tr>
<td class="org-left">tab-bar-close-tab</td>
<td class="org-left">tab to be removed from tab bar</td>
<td class="org-left">Tab perisists</td>
<td class="org-left">(wrong-type-argument number-or-marker-p nil)</td>
</tr>

<tr>
<td class="org-left">tab-bar-close-other-tabs</td>
<td class="org-left">other tab to be removed from tab bar</td>
<td class="org-left">Tabs perisist</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-undo-close-tab</td>
<td class="org-left">last closed to be undone</td>
<td class="org-left">Since tabs are not removed, last "deleted" just gets focus until exhausting tab-bar-mode's undo stack</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-move-tab-right</td>
<td class="org-left">current tab to be moved right</td>
<td class="org-left">tab is not moved</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-move-tab-left</td>
<td class="org-left">current tab to be moved left</td>
<td class="org-left">tab is not moved</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-rename-tab</td>
<td class="org-left">tab to be renamed to input</td>
<td class="org-left">tab is not renamed</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-move-tab-to-frame</td>
<td class="org-left">current tab to be moved to new frame</td>
<td class="org-left">tab is not moved</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">tab-bar-close-tab</td>
<td class="org-left">tab to be removed from tab bar</td>
<td class="org-left">Tab perisists</td>
<td class="org-left">(wrong-type-argument number-or-marker-p nil)</td>
</tr>
</tbody>
</table>

For my personal use-case, I'd like definitely like to be able use the following while bufler-workspace-tabs-mode is enabled:
\`tab-bar-switch-to-tab\`, \`tab-bar-move-tab-right\`, \`tab-bar-move-tab-left\`.

I'm not sure if that complicates the design of things too much, but just my two cents.

Some of the other commands I don't use as much, but it'd be great if they worked similar to how they work without bufler-workspace-tabs-mode enabled.

**Comment by progfolio** [comment]
> Did I miss anything?

Got them all. I assumed most of these were by design, but thought I'd double check. 

> The functionality of setting the current frame's workspace is handled by bufler-workspace-frame-set, so tab-bar-switch-to-tab seems redundant. Maybe we could have it call bufler-workspace-frame-set when bufler-workspace-tabs-mode is active.

Not a bad idea!

**Comment by alphapapa** [comment]
@progfolio  I think that should take care of `tab-bar-switch-to-tab`.  Please let me know if does for you.  Thanks.

**Comment by progfolio** [comment]
Thanks! It does allow the command to execute successfully. One note:

The selection buffer includes all of the subcategories. e.g.
```emacs-lisp
Dir: ~/.emacs.d/
Dir: ~/.emacs.d/ » Projectile: .emacs.d
*Special*
*Special* » *Helm*
*Special* » *Helm* » helm-major-mode
*Special* » special-mode
*Special* » **Special**
```
Selecting any of the subcategories correctly creates a tab with the tab-bar-list of buffers you would expect, but any navigation away from that tab removes the subcategory tab. If the idea is for the tab bar to be a static list of the top-level categories, it would probably be better to filter the subcategories from the selection menu if it's not a pain to implement. So you'd end up with:
```emacs-lisp
Dir: ~/.emacs.d/
*Special*
```
when invoking tab-bar-switch-to-tab.

**Comment by alphapapa** [comment]
The current behavior is the intended behavior.  The tab-bar lists all top-level groups, as well as whatever the selected group is, regardless of its level.  The `bufler-workspace-frame-set` command offers all groups at all levels.

We could override `tab-bar-switch-to-tab` with a new command that only offers visible tabs, and that might make sense.  On the other hand, it would be less flexible, and the user would have to call `bufler-workspace-frame-set` specifically to select groups at other levels.  So I'm not sure if it's worth it at this time.

What do you think?

Thanks.

**Comment by progfolio** [comment]
That stands to reason. I'm happy to have the command working! Keeps my fingers happy. Thanks again.
