### ISSUE TITLE
deeper levels

### ISSUE THREAD

**Issue by seblemaguer** [alphapapa/bufler.el#20]
Hello,

I am sorry in advance as I am pretty sure my question is completely stupid at this stage. Nevertheless, here it is :D.

I try to configure a group with a "deeper level architecture". My plan is to get something  like this:

```
Chatty
   |
   +------------ ERC  <buffers with mode name matching "^erc-.*">
   |              |
   |              +------------ Channels
   |              |               |
   |              |               + <buffers with name matching "^#">  
   |              |
   |              +------------ Server
   |              |               |
   |              |               + <buffers with name matching "^[a-zA-Z0-9.]*:[0-9]\\{4\\}">
   |              |
   |              +------------- Remaining
   |                              |
   |                              + everything which is neither a channel or a server
   |
   ...
```

I want to keep the name of the section like this as well as I find it clearer. My main problem comes from the main condition (the ERC part) and how to force the creation of the groups Channels, Server and Remaining. Do you have a direction I can start to look at?

Thanks a lot

**Comment by alphapapa** [comment]
Hi Sébastien,

Your question isn't stupid at all, but I think the default groups already show how that would be done.  As well, your customized grouping rules already seem to do something like that.  So I think there's already a direction to look at.  :)  If you can ask a more specific question, maybe I can give a more direct answer.

In case another example helps, here's how I added some Bufler support to `matrix-client`: https://github.com/alphapapa/matrix-client.el/blob/59c792423fd0503f1375f356bec56130e65d3b51/matrix-bufler.el#L101  It shows a list like this: 

![mb](https://user-images.githubusercontent.com/601365/77118264-d4726600-6a01-11ea-94e4-adb786f6a1aa.png)

**Comment by seblemaguer** [comment]
I think my logic is flawed as I don't understand why this

```elisp
 (group (group-or "Chatty"
                                    (group (mode-match "ERC" (rx bos "erc-")))
                                    (group (name-match "*Slack*" (rx bos "*Slack"))))
                          )
```

leads to this error

```
Debugger entered--Lisp error: (invalid-function (#f(compiled-function (&rest args2) #<bytecode 0x13d450dd0ab03682>)))
```

**Comment by alphapapa** [comment]
`group-or` can't create subgroups like that.  It creates one subgroup.  Remove the `(group ...)` wrapping around those `mode-match` and `name-match` rules.

**Comment by seblemaguer** [comment]
Ok thanks a lot. Thanks to your answer I clicked and got the part of the logic I was missing :)

**Comment by alphapapa** [comment]
You're welcome.  I don't feel like I've fully grokked it either, and I hope to make improvements to the grouping rules in the future.  As it stands, a little experimentation is sometimes needed.

**Comment by seblemaguer** [comment]
:), it is just that I missed the fact you defined first the condition feeding the whole group and then describe the subgroups. It is my mistake as it was actually clear from the example :)
