### ISSUE TITLE
bufler-switch-to-buffer: Behavior when no matching buffers

### ISSUE THREAD

**Issue by antifuchs** [alphapapa/bufler.el#22]
So I've been using `bufler-switch-to-buffer` quite happily for a few days now, but today was the first time I hit a limitation: I meant to create a new buffer by typing a new name, like `*foo*`, expecting that it would be created with that name verbatim. However, what bufler did was a bit baffling: It switched to a completely unrelated, existing buffer.

I'm wondering what a good behavior would be, under the circumstances:

* If no frame workspace is set, I think it's completely reasonable to create (or prompt to create the buffer with the given name).
* If one _is_ set, that's an open question: The buffer name entered might match an off-workspace buffer (e.g. enter `*scratch*` in a non-"Special" workspace). I see two options:
  * switch to the matching buffer (maybe even show it on the list of available completions? Does that work?)
  * prompt to create a second one.
  * do nothing? (That's my least favorite)

Does that sound reasonable? If you agree, I can try to cobble something together in a PR (:

**Comment by alphapapa** [comment]
Probably the simplest and "most correct" thing to do now would be to pass the flag to `completing-read` to REQUIRE-MATCH: https://github.com/alphapapa/bufler.el/blob/39e756a23196d12792a3af4a06ab024d8235ee19/bufler-workspace.el#L107  I probably should have done that already.

`switch-to-buffer` can create a new buffer, but I'm not sure that `bufler-switch-buffer` should necessarily do that as well.  It's intended to switch between existing buffers.  I think if you want to make a new buffer, maybe you should use `switch-to-buffer`.

What do you think?  Thanks.

**Comment by antifuchs** [comment]
Ah! That's reasonable - setting the `require-match` parameter is the right thing here. 

While it's always hard to get over the finger memory, I think I'll manage once I get the hang of using the separate switch-to-buffer command... I could also just start creating more temporary files (:

**Comment by alphapapa** [comment]
You might find the `make-temp-file` package helpful.  I use it all the time.

**Comment by alphapapa** [comment]
@antifuchs I think that should take care of it.  Please let me know if you find any other issues.  Thanks.

**Comment by antifuchs** [comment]
Works great now, thank you!
