### ISSUE TITLE
Symbol’s function definition is void: map-put!

### ISSUE THREAD

**Issue by gonewest818** [alphapapa/bufler.el#23]
I'm getting this error when I install `bufler` with `use-package` in Emacs 27, then quit, and then launch Emacs 26.3.

```
Error (use-package): bufler/:init: Symbol’s function definition is void: map-put!
Error (use-package): bufler/:catch: Symbol’s function definition is void: map-put!
```

But not the other way around, i.e. if I install `bufler` in an Emacs 26 session then I can run either Emacs 26 or Emacs 27.

**Comment by alphapapa** [comment]
Emacs byte-code files are not guaranteed to be compatible with older versions of Emacs.

**Comment by gonewest818** [comment]
gotcha.
