### ISSUE TITLE
bufler hydra remains open

### ISSUE THREAD

**Issue by lerouxrgd** [alphapapa/bufler.el#25]
To reproduce:
* Run `bufler`
* Press `?` to open hydra help
* Press `?` again, the bufler buffer gets killed and the hydra help remains

**Comment by alphapapa** [comment]
Unfortunately I don't see a straightforward way to fix that with `pretty-hydra`.

Fortunately, there seem to be two simple workarounds:

* Press `q` to exit the Hydra.
* Don't press `?` while in the Hydra.

**Comment by alphapapa** [comment]
Copying my comment from the PR:

> That changes the fundamental behavior of the hydra so that any action exits the hydra.  It also turns `?` into the key to exit the hydra, which it is not intended to be.  Finally, I'm not sure if calling `quit-window` directly will always work correctly.
> 
> I appreciate the patch, but I don't think this is the way to go.

Would you explain why you think this issue even needs to be fixed?  `?` is not listed as a valid key in the hydra, and users who press it by accident can simply press `q` to exit the hydra.  I don't think this is a significant problem.

**Comment by lerouxrgd** [comment]
Indeed it changes a bit the behavior of the hydra which is why I wanted to hear your opinion about it. I am not a power user of hydra in general but I am quite used to the behavior of the one from `treemacs`. And this is what this PR tries to imitate, however this was just a suggestion.

As for why I think the current behavior is odd and should be fixed, well I can easily run into situations where the hydra sticks around. The workflow I described above is one way, another one could be:
* Run `bufler`
* Press `?` to open hydra help
* Press `RET`to switch to the selected buffer, then it switches buffer but the hydra sticks around. If I press `q` to quit it, then the buffer is switched back to the previous one. If I press anything else, I get the message: `Wrong type argument: (or eieio-object class), nil, obj`.

**Comment by alphapapa** [comment]
Thank you, now I understand.  I think your patch is the right way to do it.  :)

**Comment by alphapapa** [comment]
BTW, for future reference, you should generally propose PRs from a branch on your fork rather than from your `master` branch.  That makes it safer for me to push amendments before merging.
