### ISSUE TITLE
bufler-switch-buffer: Default to "other" buffer?

### ISSUE THREAD

**Issue by antifuchs** [alphapapa/bufler.el#27]
In a workspace, using `bufler-switch-buffer`, the default (topmost sorted) buffer often is the buffer I'm currently in. You can reproduce the current behavior by setting the frame-workspace in a frame with one buffer, opening a second buffer, and then using `M-x bufler-switch-buffer` twice in a row: I'd expect the buffer that is not currently active to be selected.

It would be great (since I use that b-s-b on `C-x b` and finger memory for "let's go back" is so strong), to be able to switch to the `other-buffer` from the buffer I'm currently in, like `switch-buffer` does it via the `read-buffer-to-switch` function: 

```emacs-lisp
      (read-buffer prompt (other-buffer (current-buffer))
                   (confirm-nonexistent-file-or-buffer))
```

**Comment by alphapapa** [comment]
Thanks, that's a good idea.  I think that should do it.  Please let me know if that works for you.
