### ISSUE TITLE
Emacs requirement version 26.3

### ISSUE THREAD

**Issue by micah** [alphapapa/bufler.el#29]
Hi,

Emacs in Debian Stable is 26.1, but Bufler requires 26.3. Is there any way to relax that dependency so that Debian Stable installs can get bufler installed? Melpa says its incompatible, because of this.

Thanks!

**Comment by alphapapa** [comment]
Hi,

I don't have Emacs 26.1 available to test with.  If you can confirm that Bufler works on 26.1, I'll update the header accordingly.

But Emacs is easy to upgrade on Debian, so I recommend upgrading Emacs instead.  I'm surprised that 26.3 is not available in backports, but I'm sure there's a repo that has it, and it's also trivial to build and install on Debian.

**Comment by micah** [comment]
alphapapa <notifications@github.com> writes:
> I don't have Emacs 26.1 available to test with.  If you can confirm that Bufler works on 26.1, I'll update the header accordingly.

Sure, I can try to do that. What would be the way to install it without
melpa/quelpa?

> But Emacs is easy to upgrade on Debian, so I recommend upgrading Emacs instead.  I'm surprised that 26.3 is not available in backports, but I'm sure there's a repo that has it, and it's also trivial to build and install on Debian.

At the moment, Emacs 26.3 is only available in Debian Unstable. Until it
propagates to testing, it is ineligible for backports.

-- 
        micah

**Comment by alphapapa** [comment]
> Sure, I can try to do that. What would be the way to install it without melpa/quelpa?

You could just load the Elisp files directly.

> At the moment, Emacs 26.3 is only available in Debian Unstable. Until it propagates to testing, it is ineligible for backports.

It's still in unstable?!  Emacs 27 is going to be released soon!  Good grief, it's really annoying that Debian isn't keeping up with Emacs.  Emacs 26.2 was released a year ago now, and 26.3 in August.

**Comment by micah** [comment]
alphapapa <notifications@github.com> writes:

>> Sure, I can try to do that. What would be the way to install it without melpa/quelpa?
>
> You could just load the Elisp files directly.

Seems to work fine, I just had to install pretty-hydra.

**Comment by alphapapa** [comment]
Thank you.

**Comment by alphapapa** [comment]
Since Debian 11 is out now and has Emacs 27, I'm closing this.
