### ISSUE TITLE
`bufler-switch-buffer` with just buffer name

### ISSUE THREAD

**Issue by jur0** [alphapapa/bufler.el#35]
Is it possible to display only buffer name without its "outline path" using `bufler-switch-buffer`?

This would be useful when a workspace is active - I don't really care much about the whole path.

**Comment by alphapapa** [comment]
Yeah, that would probably be a good thing to do.  I'll plan to work on that feature.  Thanks.

**Comment by alphapapa** [comment]
I must have done this at some point, because it appears to be the case now.  :)
