### ISSUE TITLE
Emacs turns unresponsive with a long delay when killing buffer with a large number of buffers open

### ISSUE THREAD

**Issue by akshaybadola** [alphapapa/bufler.el#36]
When I kill a buffer with `*bufler*` in any section and when a large number of buffers are open; more than 700 in the present case; there's a long delay and emacs turns unresponsive. A quick profiler report suggests that `bufler-group-tree` is consuming a lot of CPU. I'm hypothesizing that it's just updating the entire `*bufler*` buffer which seems overkill for each kill operation especially if it's a single file. Perhaps some caching and update of only the corresponding section can be done?

**Comment by alphapapa** [comment]
The grouping functions are applied to each buffer when the grouping is updated; there's no way around that.

Caching is already implemented, but as a whole, not for individual buffers or groups.  Doing it by buffer or section would essentially invert the data structure and add an additional step to translate from one to the other, so I probably wouldn't be interested in that.

700 buffers is a lot.  I've never used anywhere near that many.

If you're finding that performance is an issue, I'd suggest trying the native-comp branch.  You can easily try it with this Docker image: https://hub.docker.com/r/andreacorallo/emacs-nativecomp

**Comment by akshaybadola** [comment]
Thanks for the clarifications and suggestions. I would take a look at the data structure and code (just to see how exactly it's implemented) but I'm too occupied with other things right now. I'll check that native-comp. I'll close the issue for now and perhaps update if there's any new insight.
