### ISSUE TITLE
How to create nested groups in buffler?

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#37]
I use exwm and have the following two groups, one for all exwm buffers and one for just the Firefox ones, which are the majority of exwm buffers for me (note that I rename my exwm buffers to be the first initial of the program name and colon, as "F :" below).

```elisp
(group
 (group-and "*Firefox*"
	    (mode-match "*EXWM*" (rx bos "EXWM"))
	    (name-match "*Firefox*" (rx bos "F :"))))
(group
 (mode-match "*EXWM*" (rx bos "EXWM")))
```

These work as expected, and is an ibuffer-like way of doing it. But to utilize buffler, this really ought to be exwm a a parent of firefox. I don't see in the readme, How do I create this nested structure?

**Comment by alphapapa** [comment]
This is covered in the readme:

> A list of functions defines a subgroup which short-circuits other groups at the same level, preventing further grouping outside of the subgroup’s functions.

Admittedly, it's not easy to explain, so the readme also says:

> If this explanation doesn’t seem clear, please see the examples.

I think if a user studies the example and the corresponding screenshot, it can be deciphered.  Still, it's not necessarily intuitive.  If you have any suggestions for improving the documentation in this area, I'd welcome them.

Anyway, try this (with `bufler-groups` set to the default value):
```el
(setf bufler-groups
      (append (bufler-defgroups
                (group
                 (mode-match "*EXWM*" (rx bos "EXWM"))
                 (name-match "*Firefox*" (rx bos "F :"))))
              bufler-groups))
```
I think that will do what you're looking for.

**Comment by WorldsEndless** [comment]
Ah -- I didn't know it worked like that with multiple lines in `group`. That did the trick!

For reference, I chose to avoid `append` since it's a little stateful and opaque to me, so just with defn I did this:

```lisp
(setf bufler-groups
	   (bufler-defgroups
	     (group
	      (auto-workspace))
	     (group
	      (mode-match "*EXWM*" (rx bos "EXWM"))
	      (name-match "*Firefox*" (rx bos "F :")))
	     (group
	      (group-or "*Help/Info*"
			(mode-match "*Help*" (rx bos "help-"))
			(mode-match "*Info*" (rx bos "info-"))))
	     (group
	      (group-and "*Special*"
			 (lambda (buffer)
			   (unless (or (funcall (mode-match "Magit" (rx bos "magit-status"))
						buffer)
				       (funcall (mode-match "Dired" (rx bos "dired"))
						buffer)
				       (funcall (auto-file) buffer))
			     "*Special*")))
	      (group
	       (name-match "**Special**"
			   (rx bos "*" (or "Messages" "Warnings" "scratch" "Backtrace") "*")))
	      (group
	       (mode-match "*Magit* (non-status)" (rx bos (or "magit" "forge") "-"))
	       (auto-directory))
	      (mode-match "*Helm*" (rx bos "helm-"))
	      (auto-mode))
	     (dir user-emacs-directory)
	     (group
	      (dir (if (bound-and-true-p org-directory)
		       org-directory
		     "~/org"))
	      (group
	       (auto-indirect)
	       (auto-file))
	      (group-not "*special*" (auto-file))
	      (auto-mode))
	     (group
	      (auto-projectile))
	     (group
	      (auto-project))
	     (auto-directory)
	     (auto-mode)))
```
