### ISSUE TITLE
defvar: Symbol’s value as variable is void: magit-section-mode-map

### ISSUE THREAD

**Issue by sjLambda** [alphapapa/bufler.el#38]
I get this error on M-x bufler:

`defvar: Symbol’s value as variable is void: magit-section-mode-map`

I get the same error with all M-x bufler* commands. buffer and buffer run fine. Magit also runs fine.

I see that magit-section version 2.90.1 was installed as a dependency in the folder elpa/magit-section-2.90.1/magit-section. 

Magit also has the same map file installed under elpa/magit-2.90.1/magit-section.

My config is a one-liner:

`(use-package 'bafler :ensure t)`

I'm running compiled Emacs from the latest master trunk.

===============================================
Addendum: Just ran toggle on error and trapped this error:

```
Debugger entered--Lisp error: (void-variable magit-section-mode-map)
  byte-code("\301 \302\1\10\"\210\303\1\304\305#\210\303\1\306\307#\210\303\1\310\311#\210\303\1\312\313#\210\303\1\314\315#\210\303\1\316\317#\210\303\1\320\321#\210\303..." [magit-section-mode-map make-sparse-keymap set-keymap-parent define-key "?" hydra:bufler/body "g" bufler "f" bufler-list-group-frame "F" bufler-list-group-make-frame "N" bufler-list-buffer-name-workspace "k" bufler-list-buffer-kill "s" bufler-list-buffer-save "\15" bufler-list-buffer-switch " " bufler-list-buffer-peek] 5)
  (defvar bufler-list-mode-map (byte-code "\301 \302\1\10\"\210\303\1\304\305#\210\303\1\306\307#\210\303\1\310\311#\210\303\1\312\313#\210\303\1\314\315#\210\303\1\316\317#\210\303\1\320\321#\210\303..." [magit-section-mode-map make-sparse-keymap set-keymap-parent define-key "?" hydra:bufler/body "g" bufler "f" bufler-list-group-frame "F" bufler-list-group-make-frame "N" bufler-list-buffer-name-workspace "k" bufler-list-buffer-kill "s" bufler-list-buffer-save "\15" bufler-list-buffer-switch " " bufler-list-buffer-peek] 5))
  autoload-do-load((autoload "bufler" "Show Bufler's list.\nWith prefix argument FORCE-REF..." t nil) bufler)
  command-execute(bufler record)
  execute-extended-command(nil "bufler" #("buf\ntoggle-debug-on-error\nbufler\nibuffer-list-buff..." 3 4 (read-only t) 4 13 (read-only t face selectrum-current-candidate) 13 15 (read-only t face (selectrum-primary-highlight selectrum-current-candidate)) 15 25 (read-only t face selectrum-current-candidate) 25 26 (read-only t) 26 28 (read-only t face selectrum-primary-highlight) 28 34 (read-only t) 34 36 (read-only t face selectrum-primary-highlight) 36 54 (read-only t) 54 56 (read-only t face selectrum-primary-highlight) 56 75 (read-only t) 75 77 (read-only t face selectrum-primary-highlight) 77 93 (read-only t) 93 95 (read-only t face selectrum-primary-highlight) 95 106 (read-only t) 106 108 (read-only t face selectrum-primary-highlight) ...))
  funcall-interactively(execute-extended-command nil "bufler" #("buf\ntoggle-debug-on-error\nbufler\nibuffer-list-buff..." 3 4 (read-only t) 4 13 (read-only t face selectrum-current-candidate) 13 15 (read-only t face (selectrum-primary-highlight selectrum-current-candidate)) 15 25 (read-only t face selectrum-current-candidate) 25 26 (read-only t) 26 28 (read-only t face selectrum-primary-highlight) 28 34 (read-only t) 34 36 (read-only t face selectrum-primary-highlight) 36 54 (read-only t) 54 56 (read-only t face selectrum-primary-highlight) 56 75 (read-only t) 75 77 (read-only t face selectrum-primary-highlight) 77 93 (read-only t) 93 95 (read-only t face selectrum-primary-highlight) 95 106 (read-only t) 106 108 (read-only t face selectrum-primary-highlight) ...))
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> execute-extended-command (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> execute-extended-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```

**Comment by alphapapa** [comment]
I can't see any reason for this problem, so it's probably an issue with your Emacs config.  I suggest reinstalling the relevant packages, or trying with an empty Emacs config.

**Comment by alphapapa** [comment]
As well, note that this code is invalid in more than one way:

```el
(use-package 'bafler :ensure t)
```

**Comment by sjLambda** [comment]
That was autocorrect playing havoc with bufler when I posted the error msg. Had I not spelled correctly, it wouldn't have installed from melpa and generate all those error messages. In any case, your response does not instill confidence as it indicates you're just as clueless as me.

**Comment by alphapapa** [comment]
Yes, I'm so clueless that I've published 24 Emacs packages to MELPA that have over 300,000 downloads.  I couldn't possibly have a clue what I'm talking about.

Gotta get in that parting shot, right?  Who taught you to act this way toward people you're asking for help?  You ought to be ashamed.

**Comment by sjLambda** [comment]
Sorry, late reaction to your response. Let me see if I can set my comment straight. I said I felt the lack of confidence was in me as I've already reinstalled it several times in different VMs and OSs (Mac and Linux). I even tried the latest sources from emacs trunk. I'm baffled, clueless.  My confusion and comment had nothing to do with you or your qualifications. I don't know who you are, never heard of you before. Sorry if I'm supposed to know about your greatness.

I'm just hunting down an error msg and as first recourse posted to the pkg source repository. Your response surely did not suggest wisdom of someone with 300,000 downloads. Your smart alec first response was a strong hint that you're not benefiting from all those downloads. You could've let someone else answer, or not answer at all since you had nothing to contribute other than to rub your past qualifications. 

Then you closed the issue eventhough it's not been solved. Why did you close? For all I know you could be the world's best phuck, but I'm trying to solve a very specific error message from bufler.

**Comment by alphapapa** [comment]
Did you ever follow the advice I gave you in my first response?  That is:

> I suggest reinstalling the relevant packages, or trying with an empty Emacs config.

You haven't said that you've done that yet.

**Comment by NicholasBHubbard** [comment]
I am having this same issue on emacs 27.1. I loaded emacs with only this one line in my config:
```
(require 'bufler)
```
The error I get is:
```
Symbol's value as variable is void: magit-section-mode-map
```
