### ISSUE TITLE
Enhancement idea: recent list?

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#40]
I realize that Bufler is combining ideas of ibuffer and persp/perspective/torus, so I'm not sure this idea completely fits, but it would be nice for my usecase...

I don't care so much about the persp parts of bufler, but I quite like the buffler-switch-buffers list and display; I love the way it automatically places things in categories and groups. What I really miss compared to plain ivy-switch-buffer and helm-switch-buffer, however, is the "recently visited" inclusion so that all my recents are among my choices. I know that bufler is centered on the buffer list, which obviously doesn't include buffers that aren't currently open, but this might be a worthy discussion point. Have you considered any ways of including files from the recent list in the `bufler-switch-buffer` list?

**Comment by alphapapa** [comment]
You mentioned both recent files and recent buffers, which aren't the same thing.  However, both cases would be best handled by using `helm-bufler` in a Helm command that also includes recent-buffers and recentf sources.  Those would be out-of-scope for Bufler, and they're already handled by Helm.
