### ISSUE TITLE
Consider option to not refresh VC state of remote buffers

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#41]
I'm enjoying buffler very much; thanks!

Tramp is a core part of my day-to-day work, including tramp login a sudo. However, while doing that, I find that pressing `C-x b` (bufler-switch-buffer) apparently re-logs into or renews my buffers every time so I have lengthy pauses while it does:

> Tramp: Found remote shell prompt on ‘yvbeta’ Tramp: Opening connection for root@yvbeta using sudo&#x2026;done

every single time. Is there anything I can do about this so I can keep using buffler while in my remote Tramp workflows without this lag?

**Comment by alphapapa** [comment]
I'm glad you're liking it.

See the `bufler-vc-` options in the `bufler` customization group.  Disabling one or both of those will probably solve it.

Maybe an option should be added to only update VC status on local buffers.

**Comment by WorldsEndless** [comment]
Ah! Thanks. Yeah, such an option would probably be useful. What is the VC status for in general in Bufler?

**Comment by alphapapa** [comment]
Did changing one of those options solve the problem?

> What is the VC status for in general in Bufler?

I'm not sure what you mean.

**Comment by WorldsEndless** [comment]
Ah; I see now that VC status is a column in the bufler list. I've not paid attention to that.

I have not tried that solution yet, but I'm worried because I found all the vc- things were already nil...

I'll report back after I've given it a thorough testing this morning.

**Comment by WorldsEndless** [comment]
Ok; verified. I am no longer seeing the sudo reconnect messages every time I do bufler-switch-buffer.

**Comment by alphapapa** [comment]
Thanks.

FYI, I forgot that one of the variables, `bufler-vc-state`, is obsolete and no longer has any effect.  Instead, you can remove the VC column from `bufler-columns`, if you never want to see VC state or have a buffer's VC state checked.

**Comment by WorldsEndless** [comment]
Already done (removing the column, that is) :)

**Comment by alphapapa** [comment]
FYI: @bqv @WorldsEndless https://github.com/alphapapa/bufler.el/commit/30898f69d1227e29cc9ae19969c88906495643de
