### ISSUE TITLE
Improve window management for bufler-list

### ISSUE THREAD

**Issue by eblanton** [alphapapa/bufler.el#42]
I normally run a full-screen Emacs with a vertical split (`C-x 3`).  When I start `M-x bufler` in this environment, it reuses one of the existing windows (this may be due to customization, but I don't think so; it looks like `bufler` uses `pop-to-buffer`, which uses `display-buffer`, which is customizable but doesn't seem to be customized in my installation).  When I select a buffer with `bufler-list-buffer-switch`, bufler calls `delete-window` on this window, which is not what I want.

I think that delete window should either be optional (e.g., `(defcustom bufler-delete-window-on-switch)` or (and I think this is more likely, but also probably more controversial) the switch command should simply be redefined as something like:

```
(bufler-define-buffer-command switch "Switch to buffer."
  (lambda (buffer)
    (pop-to-buffer-same-window buffer)
  :refresh-p nil)
```

I note that there is even a comment in the switch command noting that it's difficult to "get it right" under the current regime.  For me, that's probably an indication that the default behavior is doing too much, and it should either be replaced by a user-defined callback or something that simply uses the built-in Emacs window management along with the user's configured preferences.

There may even be an argument that `pop-to-buffer` is the right function, but I don't think so; I think the user would expect `*Bufler*` to be replaced with the selected buffer.

This is a low priority report for me; I have defined a bufler command `show` which is exactly the above, and the problem is "fixed" from my perspective.  I am reporting it only because it was a surprising behavior to me, and I thought you may wish to know about it.  (Both `buffer-list` and `ibuffer` behave as expected in this fashion, although bufler is clearly better in other ways!)

**Comment by alphapapa** [comment]
Yes, this definitely needs to be improved.  I coded it to behave basically how I would want it to, but it should be configurable according to a user's preference.  There are various ways this could be coded, but I don't know what is the most idiomatic or standard way to do this in Emacs (i.e. control how and where a window is displayed in a user-configurable way, while also properly cleaning up such a window when necessary).  I'd prefer to use standard, built-in methods of handling this rather than writing bespoke window-management code.  So I guess some research needs to be done.  (And if I find an answer, I should probably add it to https://github.com/alphapapa/emacs-package-dev-handbook)

**Comment by mohkale** [comment]
Yeah. Personally I'm forcing bufler to start up in the current window (it's what I'm used to from `ibuffer`).

```lisp
  (push (cons (rx "*Bufler*")
              '(display-buffer-reuse-window
                display-buffer-same-window))
        display-buffer-alist)
```

and the current switch command deletes any the window I switch to immeadiately after switching.

**Comment by alphapapa** [comment]
@eblanton @mohkale Please see the new option I just added.  It should allow you to configure the behavior to your preferences.  Please let me know how it works for you.

Answering my own question:

>  There are various ways this could be coded, but I don't know what is the most idiomatic or standard way to do this in Emacs (i.e. control how and where a window is displayed in a user-configurable way, while also properly cleaning up such a window when necessary). I'd prefer to use standard, built-in methods of handling this rather than writing bespoke window-management code. So I guess some research needs to be done. (And if I find an answer, I should probably add it to https://github.com/alphapapa/emacs-package-dev-handbook)

I used the ACTION argument to `display-buffer`, which seems like the idiomatic way to do it in Emacs.

**Comment by mohkale** [comment]
I haven't used bufler since I raised this issue but just tried it out again and everything seems to be working. And it looks a lot nicer than I remember. Thnx.

**Comment by alphapapa** [comment]
Thanks.
