### ISSUE TITLE
Auto refresh?

### ISSUE THREAD

**Issue by jasonmj** [alphapapa/bufler.el#48]
Is there a way to make bufler automatically refresh when buffers change?

**Comment by alphapapa** [comment]
No, and it might not be a good idea to do so in all cases.  The way Bufler works, by applying predicate functions to buffers, can be slow when there are many buffers, depending on the configured grouping rules.

If you want to do that, I have no objection to implementing it as an option.  However, I don't know what the appropriate way to hook in such an option would be.

**Comment by jasonmj** [comment]
That makes sense. Thanks for the response. Closing.
