### ISSUE TITLE
Long titles push columns out of view-port

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#50]
When, somewhere in my list of buffers, something has an exceptionally long title, it pushes the entire column -- and all the remaining columns -- out of view, rendering buffler-list almost not useful. I don't see a customization option for this; is there a solution to limit columns to some width?

**Comment by alphapapa** [comment]
There is not currently such a solution.  See https://github.com/alphapapa/bufler.el/blob/d623605be961316be378ffcd1e97a85069f2f7cc/bufler.el#L679

**Comment by WorldsEndless** [comment]
Fixed in PR #51

**Comment by alphapapa** [comment]
Thanks.

**Comment by alphapapa** [comment]
@WorldsEndless FYI, I added a more flexible solution that works for multiple columns.
