### ISSUE TITLE
buffler path can get too long, needs abbrev or trunc

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#61]
Previously issue #50  noted the filename getting out of hand. Likewise can the file path get out of hand -- especially when using eww (and the path is the entire web address), or when working in deeply nested dirs or on long paths on remote servers (Tramp). Some kind of truncation would be good here, probably like Doom or others do for the filename that appears in the mode-line.

![bufler-filepath](https://user-images.githubusercontent.com/5042778/109659758-44033780-7b25-11eb-9c19-d44e736d0110.png)

**Comment by WorldsEndless** [comment]
In addition to path-specific computation, it would make sense to have a "max length" for every column, or an option to make all of them fit on screen. Fit on screen would be ideal, but I'm sure it's far easier in CSS than it is in emacs.

**Comment by alphapapa** [comment]
I added an easy way for columns to optionally have a max-width specified.  Some kind of "fit every column on the screen" option sounds complicated.  :)  But if you have any algorithm or sample code to suggest, I might be interested, because it could be useful in other projects too.
