### ISSUE TITLE
Open file other window with <RET> but not close *Bufler* window

### ISSUE THREAD

**Issue by zy9306** [alphapapa/bufler.el#62]
When I in *Bufler* window and hit <RET> in some item, then *Bufler* window closed，how to keep *Bufler* window？

**Comment by zy9306** [comment]
I got a fork and modify the switch action，it works. I would be very happy if you could provided some custom configuration. Thank you for your excellent work.

**Comment by alphapapa** [comment]
This feature is already provided.  See https://github.com/alphapapa/bufler.el#bindings
