### ISSUE TITLE
native-comp problems with bufler tab-bar functionality

### ISSUE THREAD

**Issue by dcunited001** [alphapapa/bufler.el#68]
i can't quite get the `tab-bar` functions to work. i use doom emacs and i've removed as many references to its own `+workspaces` concept as i can, but i still can't quite get bufler to work. here's the stack track i get when running `(tab-bar-new-tab)` or `(bufler-workspace-tabs-mode)`. attempting to toggle the frame's tab bar doesn't work with either `(toggle-frame-tab-bar)` or by running `(bufler-workspace-mode)` twice. 

```emacs-lisp
Debugger entered--Lisp error: (invalid-function ((&plist :name :path) workspace))
  ((&plist :name :path) workspace)()
  #f(compiled-function (workspace &optional type) #<bytecode -0x3c3eaae35942352>)((:name ("*Special*") :path ("*Special*")))
  mapcar(#f(compiled-function (workspace &optional type) #<bytecode -0x3c3eaae35942352>) ((:name ("*Special*") :path ("*Special*"))))
  bufler-workspace-tabs()
  tab-bar-format-tabs()
  #f(compiled-function (format) #<bytecode -0x16947f291f641f48>)(tab-bar-format-tabs)
  tab-bar-format-list((tab-bar-format-history tab-bar-format-tabs tab-bar-separator tab-bar-format-add-tab))
  tab-bar-make-keymap-1()
  tab-bar-make-keymap(ignore)
  redisplay_internal\ \(C\ function\)()
```

various arbirtary stack traces appear for me when using Bufler's tab-bar functionality (which i think will be what emacs users turn to from centaur-tabs), however, they all seem to crash in `fns.c` in the Emacs C source directory. I've got the native-comp debugging configured with my emacs C-source path. Somewhat confusingly, these bugs proceed differently depending on whether i've run `(+doom/reload-autoloads)` to regenerate the `~/.emacs.d/.local/autoloads.28.0.50.el` file. The first Emacs session (or two?) that i run after regenerating this file seem to be much smoother, with bufler's tab-bar functionality quickly becoming unusable. the stack traces I before the `autoloads.*.el` file is corrupted seem to be different.

`bufler-list` seems to group stuff correctly. here's what i'm seeing there. 

![emacs-bufler-screenshot](https://user-images.githubusercontent.com/782627/117643797-caa44880-b156-11eb-8da8-20c786c08363.png)

I do plan on changing the default groupings once i get everything working. this package Bufler along with Burly seem to be very useful and handle window/frame management almost as ideally as i'd like. (and i've examined like a dozen different packages/methods for doing so). You have some fantastic packages. I may have some mild "[CVI](https://en.wikipedia.org/wiki/Cortical_visual_impairment)-like" dyslexia, so Prism helps me a lot in processing groups of lisp expressions.

**Comment by dcunited001** [comment]
Here's what i'm seeing after reloading the `autoloads.*.el` file.

**Comment by gagbo** [comment]
It’s doom-specific, you can create an issue for that but it’s going to be a long one to solve and nothing will happen before the CLI has been changed probably. Theoretically running `doom build` should fix the `(invalid-function ((&plist :name :path) workspace))`. And it’s not related to Doom workspaces, see #47 

Anyway, you’re going to have the error as long as bytecompiling the autoloads file produces a warning about this expression. And it’ll stop when the warning is gone.

**Comment by dcunited001** [comment]
thanks @gagbo! it would really help to have this work. i'll update this thread again once I try this out. 

I think my doom setup is already basically running `doom build` whenever i run `doom sync`, as on some updates there are like 2500+ async tasks that must be completed. I was under the impression that, if you have native-comp emacs, then both `doom sync` and `doom build` end up running `doom compile`. however, i hadn't properly looked into much regarding native-comp emacs until very recently.

**Comment by alphapapa** [comment]
@gagbo Thanks for answering this.

@dcunited001 I'm afraid I can't help you with anything Doom-related.  If you can reproduce this problem with `emacs -q`, please let me know, as it might indicate a bug in this package.  

Otherwise, it probably isn't, so I'm closing this.  But feel free to continue discussing the issue here, even if it is Doom-specific.
