### ISSUE TITLE
[suggestion] customize the space between (first level ?) sections

### ISSUE THREAD

**Issue by seblemaguer** [alphapapa/bufler.el#7]
I think that could be useful to spot easily the global section we are looking in

**Comment by alphapapa** [comment]
I'm not sure what you mean by space between them.  Do you mean the amount of indentation per level?

**Comment by seblemaguer** [comment]
no sorry, I mean increasing the skip space between two sections. The idea is to be able to have something like this:

![bufler-space](https://user-images.githubusercontent.com/4820197/75553856-1cb8ec80-5a31-11ea-8da7-445d46580903.png)

The section `Dir: ...` is separated by a significant skip from the section `Project:`. I find that more readable.

Maybe that is already possible via the magit-section configuration but I didn't check :/

**Comment by alphapapa** [comment]
I think that should do it.  Let me know what you think.  :)
