### ISSUE TITLE
bufler-list-buffer-switch does not respect window cofiguration

### ISSUE THREAD

**Issue by jmburgos** [alphapapa/bufler.el#76]
Hello,

If I split a window in two (or more parts), call bufler in one of them, select a buffer, and call `bufler-list-buffer-switch`, then the buffer is opened in a single window taking the entire frame.  Would it be possible for `bufler-list-buffer-switch` not to modify the window configuration?

Many thanks!

**Comment by WorldsEndless** [comment]
Coming from issue 77, this is almost show-stopping behavior. I have no customizations that I am aware of that should effect the action taken, but hitting enter on an item from the bufler list wills the previous window, whether in this frame or another. It doesn't seem to matter what types of buffer are displayed in the old or the new.

**Comment by jcalve** [comment]
Could we at least have an option to disable this `delete-window`? I think the behaviour seems strange because in ibuffer the behaviour is the opposite, it only deletes other windows with an optional prefix.

**Comment by dcunited001** [comment]
i think you can also address this by modifying the popup behavior in emacs. 

example with doom emacs:

```emacs-lisp
(set-popup-rules!
  '(("^\\*Bufler" :side right :width 60
    :vslot -5 :slot 3
    :modeline nil :select t :quit t))
)
```

Configuring it without doom emacs was a bit confusing for me at first. once you learn how to customize this, it's alot easier to get buffers to go where you want. The content of [set-popup-rules!](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/popup/README.org) ends up in the variable `display-buffer-alist`.

**Comment by WorldsEndless** [comment]
ping on this. After reinstalling my system a couple times I went in and made the change again, but I've been running withouth that `delete-buffer` code for over a year. At least in exwm, it makes `M-x bufler` practically unusable, and simply removing that line makes everything work as expected.
