### ISSUE TITLE
max-width variables seem un-used

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#79]
As can be seen in my screenshot, my file-names are too long in the bufler listing. I have set both of the custimize options  -- `bufler-column-Path-max-width` and `bufler-column-Name-max-width`, both of which I set to 30. I am using the latest buffler.

Note that I need them untruncated when I do a switch-to-buffer, but they make it hard to use bufler-list.

> GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0) of 2021-09-01
> Bufler per `a68e0eb * origin/master Notes: Update`

![image](https://user-images.githubusercontent.com/5042778/142917221-76c685da-6c40-450e-82b8-086d3af39280.png)

**Comment by alphapapa** [comment]
Hm, as far as I know they do work, but maybe something's wrong.  Can you reproduce in a clean config?

**Comment by alphapapa** [comment]
Hm, as far as I know they do work, but maybe something's wrong. Can you reproduce in a clean config?

**Comment by WorldsEndless** [comment]
I'll try with an emacs -q

**Comment by WorldsEndless** [comment]
I created an empty file named `~/Temp/a-buffer-with-a-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-really-long-name.txt`

On a clean config I got the same issue:

**Comment by WorldsEndless** [comment]
![buffler-width2](https://github.com/alphapapa/bufler.el/assets/5042778/5f76943d-6ac9-41d3-8761-0dc28fe4dc9a)

Having troubles getting Github to take that one...

**Comment by WorldsEndless** [comment]
I haven't figured out how the `:max-width` args are supposed to work, but they don't seem to be having any effect. I hardcoded some truncation values in and this works for me personally, but clearly isn't a viable solution for a public library.

**Comment by alphapapa** [comment]
Turned out to be a simple mistake in the code that I had never noticed.  Should be fixed now.  Thanks for reporting.
