### ISSUE TITLE
replace $HOME in Path on *Bulfer*

### ISSUE THREAD

**Issue by hamkido** [alphapapa/bufler.el#85]
Thank you for bufler.
I want to replace the part of $HOME in the image below with ~/. Since sometimes the file path can be very long, I want it to be shorter.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/43724352/211164426-24fa5372-6d54-4035-995d-f417dc81f24e.png">
How can I modify this part? Any guidance and help would be greatly appreciated.

**Comment by alphapapa** [comment]
Hello,

The code in question is here: https://github.com/alphapapa/bufler.el/blob/bf5fdccbae6bb6dc51e31dc282805e32bb41e412/bufler.el#L848-L852  You could use, e.g. the function `abbreviate-file-name`.  Feel free to send a PR that does that, if you like.

**Comment by hamkido** [comment]
Thanks for your help.
I try to process with replace-regexp. 
```
(replace-regexp-in-string (concat "^" (getenv "HOME")) "~" (buffer-local-value 'list-buffers-directory buffer))
```
I'm a little busy during Chinese New Year... 
After the Spring Festival, I'll check it out and if it works I'll move on to the next step to add options and prepare a PR.
