### ISSUE TITLE
Simple example to add a buffer with a certain name to Bufler's list?

### ISSUE THREAD

**Issue by s-mahm** [alphapapa/bufler.el#86]
I have a function that sends some command line output to a newly created buffer called Jira. By default this buffer is not shown in Bufler's list and I am trying to get it to show. 

Is there a simple lisp example I can use to show my Jira buffer on Bufler's list? I am not very LISP savy but have tried something like this to no success:

`(setf bufler-groups (bufler-defgroups
                      (group
                       (name-match "*Jira*"
                                   (rx bos "Jira")))))`

**Comment by SohMahmood** [comment]
Sorry for the late reply. That does show it, is it possible to remap C-x b to call C-u C-u M-x bufler instead?

**Comment by SohMahmood** [comment]
Sorry for the late reply, The key combination you mentioned dose show the buffer. Is it possible to have C-u C-u M-x bufler the default behaviour?

**Comment by alphapapa** [comment]
@s-mahm Seems that I missed your last comment.

See the customization options, e.g. `bufler-filter-buffer-fns`.
