### ISSUE TITLE
buffer-tabs-mode doesn't support sym link

### ISSUE THREAD

**Issue by adouzzy** [alphapapa/bufler.el#9]
My inbox.org is in  "~/org" which follows a symlink.

The tab-bar says "~/org". But the tab-line is empty. The xx.org buffer was classified into "*Special*" 
instead.

Buffer list is normal.

My guess is that the tab-line buffer names follows symlink which fails to match the tab-bar name.

I am on win 10 using wsl with emacs v28.0.x

**Comment by alphapapa** [comment]
Thanks for your feedback.

I'll need more specific information to understand what's going on.  My `~/org` is also a symlink to another directory, but everything works fine for me.

Please give the specific file name of the buffer that is in the Special group, e.g. `M-: (buffer-file-name (current-buffer)) RET` in that buffer.  Also please provide the expanded file name, i.e.  `M-: (expand-file-name (buffer-file-name (current-buffer))) RET`.

As you can see, the `*Special*` group is for buffers that are not file-backed.  And you can see in the code at https://github.com/alphapapa/bufler.el/blob/711847daf506cb9eaad4c4a92431d3007490b57e/bufler.el#L807 and https://github.com/alphapapa/bufler.el/blob/711847daf506cb9eaad4c4a92431d3007490b57e/bufler.el#L838 that both the buffer's filename and the group predicate's filename are canonicalized, which resolves symlinks.  So I don't know what's going on here.

**Comment by adouzzy** [comment]
Thank you for the advice. I really liked your package.

both commands says "/home/MYUSER/org/XXX.org"
I am using emacs 28.0.50, a snapshot version.
Given more testing, I think this is not only org related.

- My tab-bar says"DIR: ~/org" and the tab-line under it is empty.
- For the emacs configs, it works for both tab-bar and tab-line.
- I also tried another git repo. It suffer the same problem. Yes tab-bar, empty tab-line.
Any ideas?

**Comment by alphapapa** [comment]
> For the emacs configs, it works for both tab-bar and tab-line.

I don't know what this means.

> I also tried another git repo. It suffer the same problem. Yes tab-bar, empty tab-line.  Any ideas?

I'll need more information.

* I assume you have activated `bufler-tabs-mode`?
* When the tab-line is empty and you expect it to show buffers:
  * What is the active workspace, and what are its grouping rules?
  * Which buffers do you expect it to show, and what are their major modes, buffer names, and filenames?

It would be helpful if you would provide a copy of the `bufler-list` buffer, either as text (i.e. `C-x h M-w`, then paste here as code) or a screenshot.

**Comment by adouzzy** [comment]
By emacs configs, I mean all the *.el files I have inside ~/.emacs.d

Here is a screen shot of my tab-bar/ tab-line
This is when the tab-line is empty: I expected to see the README.md. (see bufler-list below)
![image](https://user-images.githubusercontent.com/1818289/76272566-e6505c80-62cf-11ea-8e94-ba562072f886.png)
This is when the tab-line is populated with buffer:
![image](https://user-images.githubusercontent.com/1818289/76272656-17c92800-62d0-11ea-834c-99964437f437.png)

I am using the default grouping rules.

bufler-list output:
```
*Special* (3)
  **Special** (2)
    *scratch*     144                                                                           
    *Messages*    7.9k                                                                          
  bufler-list-mode (1)
    *Bufler*      604     ~/Project/au-rule-discovery/rule-idea-exploration/                    
Dir: ~/org (1)
  org-mode (1)
    inbox.org     6.8k    /home/zzhou/org/inbox.org                                             
Dir: /home/zzhou/Project/au-rule-discovery/rule-idea-exploration/ (1)
  markdown-mode (1)
    README.md     0       /home/zzhou/Project/au-rule-discovery/rule-idea-exploration/README.md 
Dir: ~/.emacs.d/ (1)
  Dir: /home/zzhou/config/emacsd/subconfigs/ (1)
    emacs-lisp-mode (1)
      wm-conf.el  9.9k    /home/zzhou/config/emacsd/subconfigs/wm-conf.el                             
```

**Comment by alphapapa** [comment]
Thanks.  Please try the following and see if that causes the buffer to appear in the tab-line:

1.  `M-: (setf bufler-cache nil) RET`.
2.  Click on a different tab in the tab bar, then on the `au-rule-discovery` one again.

**Comment by adouzzy** [comment]
Unfortunetely, it doesn't work
please check the bufler-cache value below 
```
bufler-cache is a variable defined in ‘bufler.el’.
Its value is shown below.

Documentation:
Cache of computed buffer groups.

Value:
(199942533359928048
 ("*Special*"
  (#("**Special**" 0 11
     (face magit-head))
   #<buffer *scratch*> #<buffer *Messages*>)
  (nil
   (#("bufler-list-mode" 0 16
      (face magit-head))
    #<buffer *Bufler*>)))
 (nil
  ("Dir: ~/org"
   (nil
    (#("org-mode" 0 8
       (face magit-head))
     #<buffer handover.org> #<buffer inbox.org>)))
  (#("Dir: /home/zzhou/Project/au-rule-discovery/rule-targeting/" 0 58
     (face magit-section-heading))
   (#("ess-r-mode" 0 10
      (face magit-head))
    #<buffer sandbox.r>))
  (#("Dir: /home/zzhou/Project/au-rule-discovery/rule-idea-exploration/" 0 65
     (face magit-section-heading))
   (#("markdown-mode" 0 13
      (face magit-head))
    #<buffer README.md>)))
 ("Dir: ~/.emacs.d/"
  (#("Dir: /home/zzhou/config/emacsd/subconfigs/" 0 42
     (face magit-section-heading))
   (#("emacs-lisp-mode" 0 15
      (face magit-head))
    #<buffer wm-conf.el>))))
```

**Comment by alphapapa** [comment]
Have you activated `bufler-mode` or only `bufler-tabs-mode`?

**Comment by alphapapa** [comment]
Please evaluate this form with the `rule-discovery` workspace selected and paste the value here:
```el
(list :frame (selected-frame)
      :workspace-path (frame-parameter frame 'bufler-workspace-path)
      :buffers (bufler-buffers :path (frame-parameter frame 'bufler-workspace-path))
      :bufler-workspace-buffers (bufler-workspace-buffers))
```

**Comment by adouzzy** [comment]
I says symbol's value as variable is void: frame.

**Comment by alphapapa** [comment]
What commit of this repo are you running?

**Comment by adouzzy** [comment]
I installed using quelpa, this following is git log
```
Author: Adam Porter <adam@alphapapa.net>
Date:   Mon Mar 9 19:05:54 2020 -0500

    Add/Change: (bufler-vc-refresh)

commit 711847daf506cb9eaad4c4a92431d3007490b57e (grafted, master)
Author: Adam Porter <adam@alphapapa.net>
Date:   Sun Mar 8 07:44:25 2020 -0500

    Docs: Add basic explanation of 4 major features
```

**Comment by alphapapa** [comment]
To ensure that Quelpa has actually installed the latest commit, please do the following:

1.  Delete `~/.emacs.d/elpa/bufler*`.
2.  Restart Emacs.
3.  Reinstall Bufler.

**Comment by adouzzy** [comment]
I did that all the same. I also run a emacs -q session. no change.
Here is the funny thing. when I open a buffer ".gitignore" some wired tab got opened. see top right red part
![image](https://user-images.githubusercontent.com/1818289/76305192-cd1fce00-6318-11ea-9ae3-6ff094dee54e.png)

**Comment by alphapapa** [comment]
1.  Please post the value of that form as text, not as a screenshot.
2.  That tab has no name, because you have not yet selected a workspace in that frame.
3.  In order to fix the problem you initially described, I need you to focus on that problem and describe precisely the steps you are taking, beginning with running `emacs -q` (or, better, from the `bufler.el` git worktree, run `./makem.sh --sandbox --install-deps interactive`).

**Comment by alphapapa** [comment]
I think that should fix it.  Please let me know if it seems to fix it.  Thanks for your help.

**Comment by adouzzy** [comment]
@alphapapa  🌮  🌮 for the swift support and fix.
