### ISSUE TITLE
Subgroups and syntax?

### ISSUE THREAD

**Issue by WorldsEndless** [alphapapa/bufler.el#93]
Note: this is with exwm, so Firefox buffers are first-class buffer citizens. I used to have a single Firefox tab which contained my various social tabs with their particular settings. I decided that, in order to live a more tab-free lifestyle, I would pull those out. Ideally I could off-load that collection to Bufler to handle. But, though my catch-all Firefox setup in buffler has worked for ages, my desire to seperate a collection of Firefox tabs into their own subgroup is failing. So, two questions: Is such subgrouping possible? And, if so, what syntax do I need?

Here is my failing try:

```lisp
(group
 (name-match "*Firefox*" (rx bos "F:")) ;; this part has worked for a long time
 (group-and "Mastodon" ;; is something wrong with my syntax?
	    (name-match (rx "Mastodon\|mstdn\|qoto"))))
```

**Comment by alphapapa** [comment]
Well, you're using `rx`, but you've got `\|` in the string, which defeats the purpose of using `rx` (and it will escape those metacharacters).  The point of using `rx` is being able to write the regexp as a sexp, like `(rx (or "Mastodon" "mstdn" ...))`.

**Comment by WorldsEndless** [comment]
![image](https://github.com/alphapapa/bufler.el/assets/5042778/9c4b1da0-cf2d-4f6a-ab81-231fdacfd936)

Thanks!  I didn't realize that was the roll of `rx` and changed accordingly. With a little face change to make things a little more visible, here is my working code:

``` lisp
  (setf bufler-groups
	(bufler-defgroups
	;;; other groups...
	  (group
	   (name-match "*Firefox*" (rx bos "F:"))
	   (group-and "Mastodon" ;; is something wrong with my syntax?
		      (name-match "Mastodon" (rx (or "Mastodon" "mstdn" "qoto"))))
	   )
	   ;;; more other
	   )
```

**Comment by alphapapa** [comment]
That's great.  I wish I could get my Firefox tabs into Emacs/Bufler like that without having to use EXWM.  :)
